version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/standards-catalogue"
    schedule:
      interval: "daily"

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"

- package-ecosystem: "bundler"
  directory: "/standards-catalogue"
  schedule:
    interval: "daily"

- package-ecosystem: "docker"
  directory: "/standards-catalogue"
  schedule:
    interval: "daily"
